Test that show our failure handling in [CallGraph](../CallGraph/) works as expected.
